codecov:
  require_ci_to_pass: true
  
coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 80%
        threshold: 2%
        paths:
          - "src/"
        if_ci_failed: error
        only_pulls: false
        
    patch:
      default:
        target: 80%
        threshold: 2%
        paths:
          - "src/"
        if_ci_failed: error
        only_pulls: true
        
comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
  require_head: yes
  require_base: yes
  
ignore:
  - "tests/**/*"
  - "**/conftest.py"
  - "src/**/__init__.py"
  - "infrastructure/**/*"
